### ISSUE TITLE
cannot transfer to region EU-west-2

### ISSUE THREAD

**Issue by nicolasbriant** [pedropregueiro/migrate-ec2-secgroups#1]
The script is great. It works on the US regions, but when trying to copy from EU-west-1 to EU-west-2, it complains "migrate.py:24 [ERROR] please make sure that you set your EC2 credentials and that they are correct"
EU-west-2 is a new AWS region.  could it be that it is not declared somewhere?

**Comment by pedropregueiro** [comment]
hey @nicolasbriant, thanks!

it seems like your problem might indeed be related to the version of boto that I have in the requirements.txt file. I can't really test this at the moment, but if you try upgrading to at least [v2.45.0](http://docs.pythonboto.org/en/latest/releasenotes/v2.45.0.html) it might fix your issue since that's when they added support for eu-west-2
